from . import manage_post
from . import AgentKeyboard
from . import Ximiya_ketboard
from . import Vaksina_Keyboard
from . import callback_data
from . import locationKamitet
from . import locationAgent
from . import locationVaksina
from . import bolinmacamitet
from . import murojatKamitetlar
from . import murojatAgentlar
from . import murojat_vaksinalar
from . import referentagentkeyboard
from . import infografikakeyboard
from . import litsenziyaAgent
from . import resterKamitet
from . import Farmnadzor_komitet
from . import Nashrlar
from . import Zarur_Amaliyot